---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-secret
  namespace: jenkins
type: Opaque
data:
  # echo -n 'admin' | base64
  adminUser: YWRtaW4= # base64 encoded 'admin'
  adminPassword: YWRtaW4= # base64 encoded 'admin'
