apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: weather-service-hpa
  namespace: weather-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
