apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-and-memory-quota
  namespace: weather-service
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
